### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by Eli-YiLi** [yun-liu/LIID#1]
1. img_list/trainval_minus_segval.txt is not provided
2. roi_pooling_forward_cuda is not compiled (I used roi_pooling_forward instead)
3. mAP of pseudo mask is merely 27.5 with weights of your R50-pami.pth, instead of 34.8 in the paper.
4. The IRNet has higher mAP of pseudo mask but performs lower in mask_rcnn phase.

could you please provide the trainval pseudo mask results or update the .pth file?
and explain my doubt of 4.

thanks.

**Comment by yuhuan-wu** [comment]
Thank you for your response.
The img list file is the groups of VOCtrainval minus segmentation val images. If i do not include it in this repo,You can create it by yourself.
Our code does not test on CPU ops. So you may need to check the  corresponding requirements. 
About IRNet, we do not run this code. If you have questions about this network, please move to the IRNet official repository.
Best
