### ISSUE TITLE
About DeepLab Code with Res2Net101 backbone

### ISSUE THREAD

**Issue by zbf1991** [yun-liu/LIID#3]
It is a very interesting work and the performance with res2net101 as the backbone for weakly supervised semantic segmentation is impressive. I carefully checked all the links related to res2net101, but I found there is no implementation for the deeplab using res2net101. 

I want to know if you can share your deeplab code using res2net101 as the backbone? Thanks.

**Comment by yuhuan-wu** [comment]
With pleasure! Could you provide an e-mail address?

**Comment by zbf1991** [comment]
Thanks! I have sent an email to you.
